# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "65e9b2e11e0bcebe39bdb2538d7bd498"
name = "demp-app"
handle = "demp-app-5"
application_url = "https://stocks-ruby-defines-consist.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "micas-app-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://stocks-ruby-defines-consist.trycloudflare.com/auth/callback",
  "https://stocks-ruby-defines-consist.trycloudflare.com/auth/shopify/callback",
  "https://stocks-ruby-defines-consist.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
